// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gojvdkvptsxxmdjbbxou.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdvanZka3ZwdHN4eG1kamJieG91Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg1MzA0MDUsImV4cCI6MjA2NDEwNjQwNX0.SbUAAZlx8YA9pvqgN2GabTvlHHq-lnxXERJbj4f8VYo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);