// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pubpthndwtagnjzxbazn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB1YnB0aG5kd3RhZ25qenhiYXpuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgxOTIzMzcsImV4cCI6MjA2Mzc2ODMzN30.moJIH6_u83dM0uBmfyCkW-iM_YAzjIh4h4vRb3Gq2tk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);